# Generated by Django 5.2.16 on 2026-07-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
